### ISSUE TITLE
webcam selection - make it suitable for different OS

### ISSUE THREAD

**Issue by ScatteredDrifter** [nicolasseng/teamproject-objectdetection#25]
several system - mainly windows and unix - are listing their available webcams in a different manner ( either index 0 or 1 ) and thus could create an issue where one is not able to select their webcam because it was not selected correctly. 
For that we require a **system independent** selection of available webcams

**Comment by ScatteredDrifter** [comment]
@nicolasseng is it still an issue, did it occur again? 
Otherwise we can close this issue.

**Comment by nicolasseng** [comment]
> @nicolasseng is it still an issue, did it occur again?
> Otherwise we can close this issue.

no we can close it
